apiVersion: apps/v1
kind: Deployment
metadata:
  name: heavy-service-workshop
spec:
  selector:
    matchLabels:
      app: heavy-service
  template:
    metadata:
      labels:
        app: heavy-service
    spec:
      containers:
      - name: simple-container
        image: gcr.io/pontoporponto/heavy-stress:latest